# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SinoNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SinoNews

  target 'SinoNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SinoNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'NSLayoutConstraint-SSLayout'

pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'Toast'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'ZYKeyboardUtil'
pod 'GHConsole'
pod 'FCUUID'
pod 'BaiduMobStat'
pod 'MGSocialShareKit', '~> 1.0'
pod 'BGFMDB'
pod 'ReactiveObjC'
pod 'MLeaksFinder'
pod 'RTRootNavigationController'
pod 'LEETheme'
pod 'XHLaunchAd'
pod 'UINavigation-SXFixSpace'

end
